
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    apiUrl: 'http://localhost:8080/api',
    appUrl: 'http://localhost:8080',
    CLIENT_ID: '505631396907-r73ue6tma2633vjvrb8vqifvf51afsq0.apps.googleusercontent.com',
    CLIENT_SECRET: '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',
  };
